security:
  token:
    secret: mysecret-which-needs-to-be-of-at-least-512bit-long!please-change


spring:
  datasource:
    url: jdbc:postgresql://localhost/foundone
    username: postgres
    password: Start123
  jpa:
    hibernate:
      ddl-auto: update

#spring:
#  datasource:
#    url: jdbc:h2:file:./data/database
#    username: sa
#    password: sa
#  jpa:
#    hibernate:
#      ddl-auto: update

server:
  port: 8080